name: NPM Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '(release)')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install
      - name: Build Sveltestrap
        run: |
          pnpm run docs:build
      - name: Release new version
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Create new tag
        id: release
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.release.outputs.tag }}
